### ISSUE TITLE
Preserve uploaded data

### ISSUE THREAD

**Issue by sjacks26** [albany-social-media-analysis/tweetView#1]
Allow the user to pull up a dataset that has already been cached, rather than requiring the user to upload a new list of ids each time.

**Comment by nschiraldi** [comment]
To do this well, we need to authenticate the user. We can probably do this with a token/secret, but we could also do it by forcing a log in via twitter user/pass + token/secret. There may be some way to tie this into https://github.com/nschiraldi/tweetView/issues/3

Do you have an opinion on forcing this to authenticate via twitter authentication?

**Comment by sjacks26** [comment]
I'd prefer not to use Twitter authentication for this. Some folks who need to see the data might not have a Twitter account, or they might accidentally log in with a personal account that they might not want to be associated with work using this tool.

**Comment by nschiraldi** [comment]
I've been thinking about how to do this "the right way", and to get all of the databases set up correctly + authentication is a pretty big task. I was talking to Eric, and a really simple stopgap solution would be to use a google spreadsheet with URL sharing to handle the twitter ID posting and keep track of which tweets have been viewed and which have not.

So, the user would input the google spreadsheet URL, then the application would add a "viewed" column and your students can add their notes to that sheet, etc. It's not perfect and it won't work forever, but it could be a nice initial workflow. What do you think?

**Comment by sjacks26** [comment]
Hmm. I'm not sure I follow. If we did that, tweetView would still try to pull oEmbed data from Twitter each time a user went to look at the data in the google spreadsheet, wouldn't it?

**Comment by nschiraldi** [comment]
Yup but it means we no longer have to upload files (and keep track of multiple files), and we can keep track of which tweets have been already viewed and which ones have not, with little development effort. 

Instead we're using the spreadsheet as the database to track what has been viewed, and what hasn't, avoiding a bunch of back end development and get you something more useful then what we currently have, quicker. 

It shouldn't be hard to create an example.. I'll throw something together.

**Comment by sjacks26** [comment]
If you want to go this route, that's okay with me. I don't need anything quickly, though. If I were developing this myself, I'd prob focus on long term solutions rather than a short-term thing that we might not keep long term.

**Comment by nschiraldi** [comment]
Another advantage that would come from this is students can use the app to easily add notes to the spreadsheet (they wouldn't have to have two windows open per say), if that's the current workflow. In the end though, sheets would be a dependency for at least v1.

**Comment by sjacks26** [comment]
Yep, I'm confused. This would show the tweets in the spreadsheet?

**Comment by nschiraldi** [comment]
The tweets are still on the front end, it might look something like this:
![slide1](https://user-images.githubusercontent.com/8190840/49659958-658f1a80-fa13-11e8-84c1-f5f0bfc0847d.PNG)


and then the spreadsheet will auto populate based on users comments and might look like this:
![image](https://user-images.githubusercontent.com/8190840/49659209-b43bb500-fa11-11e8-8f97-80198c94c8ff.png)

**Comment by sjacks26** [comment]
This looks pretty great, actually. The auto-populate part is particularly amazing.

With this workflow, does all the oEmbed data get cached at once, or is data for each tweet pulled when the user hits "next"?

**Comment by nschiraldi** [comment]
I use the term autopopulate loosely, there will probably still have to be a "submit" button, or something like that. 

I was thinking the oEmbed would be get pulled one at a time, this would help with the twitter imposed limits.

**Comment by sjacks26** [comment]
In the long run, I'd prefer to do long-term caching of tweets. That will create more problems with rate limits, but it would also ensure that if more than one person is coding something, they see the same thing.

**Comment by nschiraldi** [comment]
Sounds good -- and since you have already archived the tweet in mongo, I'm not sure that we need to even do the oEmbed request. All oEmbed is doing is wrapping around that text, assigning the twitter ID and pumping it through a twitter API that doesn't require authentication. It's something to look into...

**Comment by nschiraldi** [comment]
Closing with respect to the google sheets implementation https://github.com/nschiraldi/tweetView/commit/687c57764099d7588c56cbbf5b17e6cccea3bfe6
