### ISSUE TITLE
Embed display options

### ISSUE THREAD

**Issue by sjacks26** [albany-social-media-analysis/tweetView#2]
If a tweet is a reply to another tweet, oembed lets you specify whether to display the tweet that is receiving the reply.
Allow the user to specify when uploading the dataset whether to show tweets that their data reply to.

**Comment by nschiraldi** [comment]
Just some thoughts, mostly for future me. 

This may be clunky with the current code. The general idea is to add a button click to turn on/off the reply. The button would force a page refresh, but maybe we can expose a javascript function that would make the transition smooth.

**Comment by sjacks26** [comment]
I think these kinds of settings are things that would be determined by the project, so they wouldn't change much once folks are using tweetView.
If there are other display options, it might make sense to move those options to the first sheet of a spreadsheet. Or, if there's an admin dashboard, put them there.
