### ISSUE TITLE
Deleted tweets/suspended accounts

### ISSUE THREAD

**Issue by sjacks26** [albany-social-media-analysis/tweetView#7]
If tweetView comes across a tweet ID for a tweet that it can't find, the whole thing crashes. Would be nice to instead show a message that the tweet no longer exists.

**Comment by nschiraldi** [comment]
We should be able to handle this gracefully. Do you have an example id?

**Comment by sjacks26** [comment]
ID_1016439857961414656. 

I'm guessing (or maybe hoping) that Twitter yells at tweetView differently if a tweet was deleted versus a user suspended, but I'm not really sure if that's true.

**Comment by nschiraldi** [comment]
There are undoubtedly other app-breaking failures we've yet to discover. I'll see what I can do about this one!

**Comment by sjacks26** [comment]
I guess my main contribution to this project is finding those failures, ha!

**Comment by nschiraldi** [comment]
there doesn't appear to be a differentiating response from the twitter API... for now I'll just display "tweet not found"

**Comment by nschiraldi** [comment]
How about this:

![image](https://user-images.githubusercontent.com/8190840/50490922-a0b2b700-09dd-11e9-8176-f2a8a2f909fe.png)

**Comment by nschiraldi** [comment]
https://github.com/nschiraldi/tweetView/commit/407fb330d43dbbd328ea23e3805052bd24df8037 addresses this issue

**Comment by sjacks26** [comment]
That's definitely good for now! 
Long term, might be worth dropping a more polished message in there. Especially if we can figure out a differentiation between deleted status and suspended user.

**Comment by sjacks26** [comment]
Oh wait, I don't have the previous and next buttons. Or a comments field.

![screen shot 2018-12-27 at 2 22 23 pm](https://user-images.githubusercontent.com/22302434/50491935-e160ff00-09e2-11e9-96f6-afed49041691.png)

Using this spreadsheet: https://docs.google.com/spreadsheets/d/1E2B0e8sk6tDj4iNp-__HDMm0tBpNzIES9zGgcqD06T8/edit?usp=sharing

**Comment by nschiraldi** [comment]
I have a feeling that's because it's looking for a 3 column spreadsheet of
tweet_id, user, ** admin entered columns

**Comment by sjacks26** [comment]
Oh right. Duh. Working now.

Now I'm trying to decide whether it makes sense for tweetView to automatically move past tweets that lead to 404s, and maybe enter an automatic comment in the Sheet that the tweet doesn't exist.

**Comment by nschiraldi** [comment]
I'll add a check for the gdrive columns and push a notification if something doesn't look right.
